sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mireli/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true mireli/react-test npm test -- --coverage

after_success:
  - docker build -t mireli/multi-client ./client
  - docker build -t mireli/multi-nginx ./nginx
  - docker build -t mireli/multi-server ./server
  - docker build -t mireli/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those iamges and push them to docker hub
  - docker push mireli/multi-client
  - docker push mireli/multi-nginx
  - docker push mireli/multi-server
  - docker push mireli/multi-worker

  # add deploy for aws
  deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "fibcalc"
    env: "Fibcalc-env"
    bucket-name: "elasticbeanstalk-us-east-1-973422094481"
    bucker-path: "fibcalc"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"


