sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mireli/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true mireli/react-test npm test -- --coverage

after_success:
  - docker build -t mireli/multi-client ./client
  - docker build -t mireli/multi-nginx ./nginx
  - docker build -t mireli/multi-server ./server
  - docker build -t mireli/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those iamges and push them to docker hub
  - docker push mireli/multi-client
  - docker push mireli/multi-nginx
  - docker push mireli/multi-server
  - docker push mireli/multi-worker


